export type RootStackParamList = {
  Tabs: undefined;
  Notifications: undefined;
  PaymentHistory: undefined;
  AnnouncementDetail: { id: string };
  Absences: undefined;
  Discipline: undefined;
  Homework: undefined;
  HomeworkDetail: { id: string };
  Resources: undefined;
  QuizList: undefined;
  QuizDetail: { id: string };
  QuizPassation: { quizId: string; tentativeId: string };
  Cantine: undefined;
  Transport: undefined;
  Bulletin: undefined;
  ChildProgress: undefined;
  ChildCalendar: undefined;
  ChildProfile: undefined;
};
