ALTER TABLE sanctions ADD COLUMN IF NOT EXISTS niveau INT NOT NULL DEFAULT 1;
ALTER TABLE sanctions ADD COLUMN IF NOT EXISTS statut VARCHAR(30) NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE sanctions ADD COLUMN IF NOT EXISTS approuve_par BIGINT;
ALTER TABLE sanctions ADD COLUMN IF NOT EXISTS commentaire_approbation TEXT;
