-- Expand vitrine_config with all the editable content blocks
-- previously hardcoded in the landing components (hero stats, badges,
-- marquee, trust strip, about, values, programs, testimonial, CTA).

ALTER TABLE vitrine_config
    ADD COLUMN hero_badge_label   VARCHAR(80),
    ADD COLUMN hero_badge_value   VARCHAR(160),
    ADD COLUMN hero_stat1_value   VARCHAR(40),
    ADD COLUMN hero_stat1_label   VARCHAR(60),
    ADD COLUMN hero_stat2_value   VARCHAR(40),
    ADD COLUMN hero_stat2_label   VARCHAR(60),
    ADD COLUMN hero_stat3_value   VARCHAR(40),
    ADD COLUMN hero_stat3_label   VARCHAR(60),
    ADD COLUMN marquee_item1      VARCHAR(60),
    ADD COLUMN marquee_item2      VARCHAR(60),
    ADD COLUMN marquee_item3      VARCHAR(60),
    ADD COLUMN marquee_item4      VARCHAR(60),
    ADD COLUMN marquee_item5      VARCHAR(60),
    ADD COLUMN marquee_item6      VARCHAR(60),
    ADD COLUMN trust_stat1_value  VARCHAR(40),
    ADD COLUMN trust_stat1_label  VARCHAR(60),
    ADD COLUMN trust_stat2_value  VARCHAR(40),
    ADD COLUMN trust_stat2_label  VARCHAR(60),
    ADD COLUMN trust_stat3_value  VARCHAR(40),
    ADD COLUMN trust_stat3_label  VARCHAR(60),
    ADD COLUMN trust_stat4_value  VARCHAR(40),
    ADD COLUMN trust_stat4_label  VARCHAR(60),
    ADD COLUMN about_eyebrow      VARCHAR(80),
    ADD COLUMN about_title        VARCHAR(160),
    ADD COLUMN about_title_accent VARCHAR(160),
    ADD COLUMN about_description  TEXT,
    ADD COLUMN about_feature1     VARCHAR(160),
    ADD COLUMN about_feature2     VARCHAR(160),
    ADD COLUMN about_feature3     VARCHAR(160),
    ADD COLUMN about_feature4     VARCHAR(160),
    ADD COLUMN about_badge_value  VARCHAR(40),
    ADD COLUMN about_badge_label  VARCHAR(60),
    ADD COLUMN value1_title       VARCHAR(80),
    ADD COLUMN value1_text        TEXT,
    ADD COLUMN value2_title       VARCHAR(80),
    ADD COLUMN value2_text        TEXT,
    ADD COLUMN value3_title       VARCHAR(80),
    ADD COLUMN value3_text        TEXT,
    ADD COLUMN program1_title     VARCHAR(80),
    ADD COLUMN program1_level     VARCHAR(60),
    ADD COLUMN program1_text      TEXT,
    ADD COLUMN program2_title     VARCHAR(80),
    ADD COLUMN program2_level     VARCHAR(60),
    ADD COLUMN program2_text      TEXT,
    ADD COLUMN program3_title     VARCHAR(80),
    ADD COLUMN program3_level     VARCHAR(60),
    ADD COLUMN program3_text      TEXT,
    ADD COLUMN testimonial_quote  TEXT,
    ADD COLUMN testimonial_author VARCHAR(120),
    ADD COLUMN testimonial_role   VARCHAR(120),
    ADD COLUMN cta_eyebrow        VARCHAR(80),
    ADD COLUMN cta_title          VARCHAR(160),
    ADD COLUMN cta_description    TEXT,
    ADD COLUMN cta_primary_label  VARCHAR(60),
    ADD COLUMN cta_primary_url    VARCHAR(255);

-- Sensible defaults so existing tenants don't see empty content
UPDATE vitrine_config SET
    hero_badge_label   = COALESCE(hero_badge_label,   'Certifie'),
    hero_badge_value   = COALESCE(hero_badge_value,   'Ministere de l''Education'),
    hero_stat1_value   = COALESCE(hero_stat1_value,   '1500+'),
    hero_stat1_label   = COALESCE(hero_stat1_label,   'Eleves'),
    hero_stat2_value   = COALESCE(hero_stat2_value,   '98%'),
    hero_stat2_label   = COALESCE(hero_stat2_label,   'Reussite'),
    hero_stat3_value   = COALESCE(hero_stat3_value,   '25 ans'),
    hero_stat3_label   = COALESCE(hero_stat3_label,   'Experience'),
    marquee_item1      = COALESCE(marquee_item1,      'Excellence academique'),
    marquee_item2      = COALESCE(marquee_item2,      'Bienveillance'),
    marquee_item3      = COALESCE(marquee_item3,      'Innovation pedagogique'),
    marquee_item4      = COALESCE(marquee_item4,      'Equipe experimentee'),
    marquee_item5      = COALESCE(marquee_item5,      'Cadre moderne'),
    marquee_item6      = COALESCE(marquee_item6,      'Suivi personnalise'),
    trust_stat1_value  = COALESCE(trust_stat1_value,  '1500+'),
    trust_stat1_label  = COALESCE(trust_stat1_label,  'Eleves formes'),
    trust_stat2_value  = COALESCE(trust_stat2_value,  '60+'),
    trust_stat2_label  = COALESCE(trust_stat2_label,  'Enseignants'),
    trust_stat3_value  = COALESCE(trust_stat3_value,  '20+'),
    trust_stat3_label  = COALESCE(trust_stat3_label,  'Programmes'),
    trust_stat4_value  = COALESCE(trust_stat4_value,  '25'),
    trust_stat4_label  = COALESCE(trust_stat4_label,  'Annees d''expertise'),
    about_eyebrow      = COALESCE(about_eyebrow,      'A propos de nous'),
    about_title        = COALESCE(about_title,        'Une education exigeante,'),
    about_title_accent = COALESCE(about_title_accent, 'tournee vers l''avenir.'),
    about_description  = COALESCE(about_description,  'Nous accompagnons chaque eleve avec rigueur et bienveillance, dans un environnement propice a l''epanouissement et a l''excellence academique.'),
    about_feature1     = COALESCE(about_feature1,     'Suivi individualise de chaque eleve'),
    about_feature2     = COALESCE(about_feature2,     'Equipe pedagogique experimentee'),
    about_feature3     = COALESCE(about_feature3,     'Equipements modernes et numeriques'),
    about_feature4     = COALESCE(about_feature4,     'Activites parascolaires riches'),
    about_badge_value  = COALESCE(about_badge_value,  '98%'),
    about_badge_label  = COALESCE(about_badge_label,  'Taux de reussite'),
    value1_title       = COALESCE(value1_title,       'Excellence academique'),
    value1_text        = COALESCE(value1_text,        'Un cursus exigeant aligne sur les meilleurs standards.'),
    value2_title       = COALESCE(value2_title,       'Bienveillance'),
    value2_text        = COALESCE(value2_text,        'Un cadre humain, a l''ecoute et respectueux.'),
    value3_title       = COALESCE(value3_title,       'Innovation'),
    value3_text        = COALESCE(value3_text,        'Des methodes pedagogiques modernes, numeriques et engageantes.'),
    program1_title     = COALESCE(program1_title,     'Maternelle'),
    program1_level     = COALESCE(program1_level,     '3 - 5 ans'),
    program1_text      = COALESCE(program1_text,      'Eveil, sociabilisation et premiers apprentissages dans un cadre chaleureux.'),
    program2_title     = COALESCE(program2_title,     'Primaire'),
    program2_level     = COALESCE(program2_level,     '6 - 11 ans'),
    program2_text      = COALESCE(program2_text,      'Acquisition des fondamentaux : lecture, ecriture, calcul et raisonnement.'),
    program3_title     = COALESCE(program3_title,     'College'),
    program3_level     = COALESCE(program3_level,     '12 - 15 ans'),
    program3_text      = COALESCE(program3_text,      'Approfondissement, autonomie et orientation pour preparer l''avenir.'),
    testimonial_quote  = COALESCE(testimonial_quote,  'Une equipe a l''ecoute, des methodes modernes, et surtout des enfants epanouis qui aiment venir a l''ecole. Nous sommes ravis.'),
    testimonial_author = COALESCE(testimonial_author, 'Salma B.'),
    testimonial_role   = COALESCE(testimonial_role,   'Parent d''eleve'),
    cta_eyebrow        = COALESCE(cta_eyebrow,        'Inscriptions ouvertes'),
    cta_title          = COALESCE(cta_title,          'Prets a rejoindre notre famille ?'),
    cta_description    = COALESCE(cta_description,    'Pre-inscrivez votre enfant en ligne en quelques minutes. Notre equipe vous contactera rapidement.'),
    cta_primary_label  = COALESCE(cta_primary_label,  'Pre-inscription en ligne'),
    cta_primary_url    = COALESCE(cta_primary_url,    '/inscription');
